# Generated by Django 3.2.12 on 2022-05-02 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 3))),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 3))),
                ('deadLine', models.IntegerField(default=1)),
                ('is_Done', models.BooleanField(default=False)),
                ('dyas_Left', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='cover-images\\default\\Login.png', upload_to='static/cover-images/%y/%m/%d/')),
                ('rated', models.IntegerField(default=0)),
                ('doneTasksNum', models.IntegerField(default=0)),
                ('doneProjectsNum', models.IntegerField(default=0)),
                ('currentTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentTeam', to='Team_Management.team')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
