# Generated by Django 3.2.12 on 2022-05-27 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('userName', models.CharField(max_length=100000)),
                ('photo', models.ImageField(default='static/cover-images/default/Login.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(default='None', max_length=100)),
                ('photo', models.ImageField(default='static/cover-images/default/Login.png', upload_to='static/cover-images/%y/%m/%d/')),
                ('rated', models.IntegerField(default=0)),
                ('doneTasksNum', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('progress', models.CharField(default='0%', max_length=100)),
                ('description', models.TextField()),
                ('is_Done', models.BooleanField(default=False)),
                ('started_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('deadLine', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('finishedDate', models.DateField(default=datetime.date(2022, 5, 27))),
                ('deadLine', models.IntegerField(default=1)),
                ('is_Done', models.BooleanField(default=False)),
                ('dyas_Left', models.IntegerField(default=0)),
                ('progress', models.CharField(default='0%', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Team_Management.profile')),
                ('dependsOn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependTask', to='Team_Management.task')),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskUser', to='Team_Management.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='Team_Management.project')),
                ('suggestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggest_to', to='Team_Management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='Team_Management.profile')),
                ('members', models.ManyToManyField(related_name='members', to='Team_Management.Profile')),
                ('messages', models.ManyToManyField(related_name='messages', to='Team_Management.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Team Request', max_length=50)),
                ('isUser', models.BooleanField(default=False)),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('teamToJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_to_join', to='Team_Management.team')),
                ('userToJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_to_join', to='Team_Management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task_suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggForUser', to='Team_Management.profile')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggFromUser', to='Team_Management.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_Task', to='Team_Management.task')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamForProject', to='Team_Management.team'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task Notification', max_length=10000)),
                ('created_Date', models.DateField(default=datetime.date(2022, 5, 27))),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forUserNoty', to='Team_Management.profile')),
            ],
        ),
    ]
