# Generated by Django 3.2.12 on 2022-05-02 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 5, 2)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadLine',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 5, 2)),
        ),
    ]
