# Generated by Django 3.2.12 on 2022-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to='Team_Management.Profile'),
        ),
    ]
