# Generated by Django 3.2.12 on 2022-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadLine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_Done',
            field=models.BooleanField(default=False),
        ),
    ]
