# Generated by Django 3.2.12 on 2022-04-24 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0002_auto_20220424_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 13, 53, 46, 415130)),
        ),
    ]
