# Generated by Django 3.2.12 on 2022-05-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0002_remove_profile_currentteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/cover-images/default/Login.png', upload_to='static/cover-images/%y/%m/%d/'),
        ),
    ]
