# Generated by Django 3.2.12 on 2022-04-24 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0003_alter_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 24)),
        ),
    ]
