# Generated by Django 3.2.12 on 2022-04-24 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0004_alter_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
        migrations.AlterField(
            model_name='task',
            name='publish_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
