# Generated by Django 3.2.12 on 2022-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0005_auto_20220424_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dyas_Left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
