# Generated by Django 3.2.12 on 2022-05-10 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0005_team_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_request',
            old_name='state',
            new_name='isAccepted',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 5, 10)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 5, 10)),
        ),
    ]
