# Generated by Django 3.2.12 on 2022-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0006_alter_task_dyas_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='publish_Date',
        ),
        migrations.AlterField(
            model_name='task',
            name='dyas_Left',
            field=models.IntegerField(default=0),
        ),
    ]
