# Generated by Django 3.2.12 on 2022-04-27 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_Management', '0007_auto_20220424_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_Date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
